name: Deploy Laravel Application to Production Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: ./.github/actions/setup
        with:
          php-version: '8.3'

      - name: Install Project Dependencies
        run: composer install --optimize-autoloader --no-dev --no-interaction --no-progress --prefer-dist

      - name: Install Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '20'

      - name: Install NPM Dependencies
        run: npm run build

      - name: Synchronize Files To Server
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "."
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: '/var/www/html'
      #          EXCLUDE: "/vendor/, /node_modules/"

      - name: Run Remote/Artisan Commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html
            php artisan migrate --force
            php artisan optimize
