name: Laravel Pint

on:
  pull_request

jobs:
  laravel-pint:
    name: Create deployment artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@2.31.1

      - name: Install Laravel pint
        run: composer global require laravel/pint

      - name: Run pint
        run: pint

      - name: Push Changes Back to repo
        run: |
          git config user.name "gh Sami Mansour" 
          git config user.email "samiman.net@gmail.com" 
          git add .
          git commit -m "Laravel Pint"
          git push