name: Laravel Multi-Stage Deployment Pipeline

on:
  push:
    branches:
      - main
      - staging

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run Tests
        run: php artisan test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Compile assets
        run: npm ci && npm run production

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'
    steps:
      - name: Deploy to staging
        run: |
          ssh ${{ secrets.STAGING_SERVER }} 'cd /var/www/staging && git pull origin staging && composer install && php artisan migrate --force'

  deploy-production:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to production
        run: |
          ssh ${{ secrets.PRODUCTION_SERVER }} 'cd /var/www/production && git pull origin main && composer install && php artisan migrate --force'

  rollback:
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Rollback on failure
        run: |
          ssh ${{ secrets.PRODUCTION_SERVER }} 'cd /var/www/production && git reset --hard HEAD~1'