name: Tests

on:
  pull_request

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          DB_DATABASE: laravel
          MYSQL_ALLOW_EMPTY_PASSWORD: yes

    env:
      PHP_VERSION: '8.3'
      PHP_EXTENSIONS: dom, curl, libxml, mbstring, zip, pcntl, pdo, gd, redis, igbinary, msgpack, lzf, zstd, lz4, memcached, gmp, :php-psr
      CACHE_KEY: extension-cache-v1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install Project Dependencies
        run: composer install -q --no-interaction --no-progress

      - name: Prep Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run Tests
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: laravel
        run: php artisan test

      - name: Push Changes Back to repo
        run: |
          git config user.name "gh Sami Mansour" 
          git config user.email "samiman.net@gmail.com" 
          git add .
          git commit -m "Laravel Pint" || exit 0
          git push